//create  and print array//
const fruits = ["Apple", "Banana", "Mongo","Orange", "Grapes"]; 
console.log(fruits); 
//access elements of an array//
console.log( fruits [0]);
console.log(fruits [4]);
//modify an array//
fruits.push ("Lemon");
console.log(fruits);
fruits.pop (5);
console.log(fruits);
fruits.unshift("jackfurit");
console.log(fruits);
fruits.shift(0);
console.log(fruits);
// using function in array//
//date//
const d = new Date ()
console.log(d)
//new date string//
const d2 = new Date ("October13, 2014 11:12:00");
console.log(d2);
